flyway.url=jdbc:postgresql://ep-curly-bread-d84i5di7.database.us-east-2.cloud.databricks.com/databricks_postgres?sslmode=require
flyway.user=stenvall.dan@gmail.com
flyway.locations=filesystem:migrations
flyway.schemas=public
flyway.baselineVersion=1
flyway.baselineDescription=baseline_country
flyway.connectRetries=3
